---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve_samples(retrieve_samples)
	load_assets(load_assets)
	generate_draft(generate_draft)
	self_consistency(self_consistency)
	format_output(format_output)
	__fallback__(<p>__fallback__</p>)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve_samples;
	retrieve_samples -.-> __end__;
	retrieve_samples --> load_assets;
	load_assets -.-> __end__;
	load_assets --> generate_draft;
	generate_draft --> self_consistency;
	self_consistency -.-> __fallback__;
	self_consistency -.-> format_output;
	self_consistency -.-> generate_draft;
	__fallback__ --> __end__;
	format_output --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
